version: '2'

services:
  mongo:
    image: mongo:3.0
    command: mongod --smallfiles --quiet
    environment:
      - RAILS_ENV=production
      - RACK_ENV=production
    ports:
      - "27017:27017"

  redis:
    image: 'redis:3.2-alpine'
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/1'

  website:
    depends_on:
      - 'mongo'
      - 'redis'
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
    env_file:
      - '.env'

  sidekiq:
    depends_on:
      - 'mongo'
      - 'redis'
    build: .
    command: sidekiq -C config/sidekiq.yml.erb
    volumes:
      - '.:/app'
    env_file:
      - '.env'

volumes:
  redis:
  mongo: