development:
  adapter: redis
  url: <%= ENV['REDIS_URL'] %>

test:
  adapter: async

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: WeatherAggregator_production

docker_development:
  adapter: redis
  url: <%= ENV['REDIS_URL'] %>
  channel_prefix: WeatherAggregator_docker_dev
